/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.UsuarioController;
import java.awt.Color;
import javax.swing.JOptionPane;
import model.Usuario;
import utils.Util;
import java.util.List;

/**
 *
 * @author iband
 */
public class FrAltUsuario extends javax.swing.JDialog {

  private int pkUsuario;

  /**
   * Creates new form FrAltUsuario
   */
  public FrAltUsuario(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    this.setLocationRelativeTo(null);
  }

  public void setPkUsuario(int pkUsuario) {
    this.pkUsuario = pkUsuario;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblDataNascimento = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        edtEmail = new javax.swing.JTextField();
        edtNome = new javax.swing.JTextField();
        edtSenha = new javax.swing.JPasswordField();
        edtDataNascimento = new javax.swing.JFormattedTextField();
        chkAtivo = new javax.swing.JCheckBox();
        imgTitulo = new javax.swing.JLabel();
        lblConfirmeSenha = new javax.swing.JLabel();
        edtConfirmeSenha = new javax.swing.JPasswordField();
        lblCodigo = new javax.swing.JLabel();
        edtCodigo = new javax.swing.JTextField();
        btnAlterarSenha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alteração de Usuário - Projeto POO");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlPrincipal.setBackground(new java.awt.Color(51, 51, 51));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        lblTitulo.setText("Alterar Usuário");
        pnlPrincipal.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        lblNome.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblNome.setText("Nome");
        pnlPrincipal.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        lblEmail.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblEmail.setText("E-mail");
        pnlPrincipal.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        lblSenha.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblSenha.setText("Senha");
        pnlPrincipal.add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        lblDataNascimento.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblDataNascimento.setText("Data Nascimento");
        pnlPrincipal.add(lblDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, 20));

        btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        pnlPrincipal.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 130, -1));

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 130, -1));

        edtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlPrincipal.add(edtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 250, -1));

        edtNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlPrincipal.add(edtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 250, -1));

        edtSenha.setEditable(false);
        edtSenha.setBackground(new java.awt.Color(204, 204, 204));
        edtSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlPrincipal.add(edtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 170, -1));

        edtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        edtDataNascimento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlPrincipal.add(edtDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 120, -1));

        chkAtivo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkAtivo.setText("Ativo");
        pnlPrincipal.add(chkAtivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        imgTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit_user.png"))); // NOI18N
        pnlPrincipal.add(imgTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblConfirmeSenha.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblConfirmeSenha.setText("Confirme a senha");
        pnlPrincipal.add(lblConfirmeSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        edtConfirmeSenha.setEditable(false);
        edtConfirmeSenha.setBackground(new java.awt.Color(204, 204, 204));
        edtConfirmeSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlPrincipal.add(edtConfirmeSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 170, -1));

        lblCodigo.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblCodigo.setText("Código");
        pnlPrincipal.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        edtCodigo.setEditable(false);
        edtCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlPrincipal.add(edtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 90, -1));

        btnAlterarSenha.setText("Alterar Senha");
        btnAlterarSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarSenhaMouseClicked(evt);
            }
        });
        pnlPrincipal.add(btnAlterarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
    gravar();
  }//GEN-LAST:event_btnSalvarMouseClicked

  private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
    this.dispose();
  }//GEN-LAST:event_btnCancelarMouseClicked

  private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnCancelarActionPerformed

  private void btnAlterarSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarSenhaMouseClicked
    if (edtSenha.isEditable()) {
      edtSenha.setEditable(false);
      edtConfirmeSenha.setEditable(false);
      edtSenha.setBackground(Color.GRAY);
      edtConfirmeSenha.setBackground(Color.GRAY);

      edtSenha.setText("");
      edtConfirmeSenha.setText("");

      btnAlterarSenha.setText("Alterar Senha");
    } else {
      edtSenha.setEditable(true);
      edtConfirmeSenha.setEditable(true);
      edtSenha.setBackground(Color.WHITE);
      edtConfirmeSenha.setBackground(Color.WHITE);

      btnAlterarSenha.setText("Cancelar");
    }
  }//GEN-LAST:event_btnAlterarSenhaMouseClicked

  private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    this.setIconImage(Util.getIcone());

    //Carregar os dados do usuário
    UsuarioController controller = new UsuarioController();

    //consultei os usuários com o código igual ao que recebi 
    // na tela de consulta
    List<Usuario> lista = controller.consultar(0, String.valueOf(pkUsuario));

    Usuario usu = null;
    usu = lista.get(0);

    //Preencher os campos como a variável usu
    edtCodigo.setText(String.valueOf(usu.getPkusuario()));
    edtNome.setText(usu.getNome());
    edtEmail.setText(usu.getEmail());
    edtDataNascimento.setText(
            Util.converterDateToString(usu.getDatanasc()));
    chkAtivo.setSelected(usu.isAtivo());
  }//GEN-LAST:event_formWindowOpened

  private void gravar() {
    //validar o preenchimento dos campos
    if (!verificarCampos()) {
      return;
    }

    //ler os campos e guardar num objeto
    Usuario usu = new Usuario();
    usu.setPkusuario(Integer.parseInt(edtCodigo.getText()));
    usu.setNome(edtNome.getText());
    usu.setEmail(edtEmail.getText());
    if(edtSenha.isEditable()){
      usu.setSenha(Util.calcularHash(new String(edtSenha.getPassword())));
    }
    usu.setDatanasc(Util.converterStringToDate(edtDataNascimento.getText()));
    usu.setAtivo(chkAtivo.isSelected());

    //enviar para o banco de dados
    UsuarioController controller = new UsuarioController();
    if (controller.alterar(usu)) {
      JOptionPane.showMessageDialog(null, "Usuário alterado");
      this.dispose();
    }
  }

  private boolean verificarCampos() {
    if (edtNome.getText().isEmpty()) {
      JOptionPane.showMessageDialog(null, "Campo 'Nome' em branco");
      return false;
    }
    if (edtEmail.getText().isEmpty()) {
      JOptionPane.showMessageDialog(null, "Campo 'E-mail' em branco");
      return false;
    }
    if (edtSenha.isEditable()) {
      if (new String(edtSenha.getPassword()).isEmpty()) {
        JOptionPane.showMessageDialog(null, "Campo 'Senha' em branco");
        return false;
      }
    }
    //^ - Início de linha
    //$ - final de linha
    //[] - conjunto de caracteres
    //+ - quantidade de vezes que o conjunto pode aparecer
    //+ - 1 ou mais vezes
    //* - 0 ou mais vezes
    //{5} - 5 vezes
    //{2} - 2 vezes
    if (!edtNome.getText().matches("^[\\p{L} ]+$")) {//a- [a-zA-Z]
      JOptionPane.showMessageDialog(null,
              "O campo 'Nome' possui formato inválido");
      return false;
    }
    if (!edtEmail.getText().matches("^[a-z0-9_.]+@[a-z0-9_.]+.[a-z]+$")) {
      JOptionPane.showMessageDialog(null,
              "O campo 'Email' possui formato inválido");
      return false;
    }
    if (!edtDataNascimento.getText().matches("^[0-9]{2}/[0-9]{2}/[0-9]{4}$")) {
      JOptionPane.showMessageDialog(null,
              "O campo 'Data Nascimento' possui formato inválido");
      return false;
    }
    if (edtSenha.isEditable()) {
      if (new String(edtSenha.getPassword()).length() < 6) {
        JOptionPane.showMessageDialog(null,
                "A senha deve ser maior que 6 dígitos");
        return false;
      }

      String senha = new String(edtSenha.getPassword());
      String confirmaSenha = new String(edtConfirmeSenha.getPassword());
      if (!senha.equals(confirmaSenha)) {
        JOptionPane.showMessageDialog(null,
                "As senhas devem ser iguais");
        return false;
      }
    }
    return true;
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FrAltUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FrAltUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FrAltUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FrAltUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        FrAltUsuario dialog = new FrAltUsuario(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarSenha;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox chkAtivo;
    private javax.swing.JTextField edtCodigo;
    private javax.swing.JPasswordField edtConfirmeSenha;
    private javax.swing.JFormattedTextField edtDataNascimento;
    private javax.swing.JTextField edtEmail;
    private javax.swing.JTextField edtNome;
    private javax.swing.JPasswordField edtSenha;
    private javax.swing.JLabel imgTitulo;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblConfirmeSenha;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
