/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.UsuarioController;
import java.io.File;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import model.Usuario;
import utils.Util;

public class FrCadUsuario extends javax.swing.JDialog {

    /**
     * Creates new form FrCadUsuario
     */
    public FrCadUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lblCadastro = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblConfirmarSenha = new javax.swing.JLabel();
        lblDataNascimento = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        edtEmail = new javax.swing.JTextField();
        edtDataNascimento = new javax.swing.JFormattedTextField();
        chkAtivo = new javax.swing.JCheckBox();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        edtSenha = new javax.swing.JPasswordField();
        lblSenha1 = new javax.swing.JLabel();
        edtConfirmarSenha = new javax.swing.JPasswordField();
        pnlFoto = new javax.swing.JPanel();
        imgFoto = new javax.swing.JLabel();
        btnEscImagem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(51, 51, 51));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCadastro.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        lblCadastro.setForeground(new java.awt.Color(204, 204, 204));
        lblCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCadastro.setText("Cadastro de usuário");
        pnlPrincipal.add(lblCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 25, 426, -1));

        lblNome.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(204, 204, 204));
        lblNome.setText("Nome");
        pnlPrincipal.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 137, -1, -1));

        lblEmail.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(204, 204, 204));
        lblEmail.setText("E-mail");
        pnlPrincipal.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 209, -1, -1));

        lblConfirmarSenha.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblConfirmarSenha.setForeground(new java.awt.Color(204, 204, 204));
        lblConfirmarSenha.setText("Confirme a senha");
        pnlPrincipal.add(lblConfirmarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 351, -1, -1));

        lblDataNascimento.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblDataNascimento.setForeground(new java.awt.Color(204, 204, 204));
        lblDataNascimento.setText("Data de nascimento");
        pnlPrincipal.add(lblDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 419, -1, -1));

        edtNome.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        pnlPrincipal.add(edtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 163, 374, -1));

        edtEmail.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        pnlPrincipal.add(edtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 235, 374, -1));

        edtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        edtDataNascimento.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        edtDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtDataNascimentoActionPerformed(evt);
            }
        });
        pnlPrincipal.add(edtDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 445, 143, -1));

        chkAtivo.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        chkAtivo.setText("Ativo");
        pnlPrincipal.add(chkAtivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 445, -1, -1));

        btnCancelar.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        pnlPrincipal.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 650, -1, -1));

        btnSalvar.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        pnlPrincipal.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 650, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adduser.png"))); // NOI18N
        pnlPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 64, -1, -1));

        edtSenha.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        pnlPrincipal.add(edtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 307, 374, -1));

        lblSenha1.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblSenha1.setForeground(new java.awt.Color(204, 204, 204));
        lblSenha1.setText("Senha");
        pnlPrincipal.add(lblSenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 281, -1, -1));

        edtConfirmarSenha.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        pnlPrincipal.add(edtConfirmarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 375, 374, -1));

        pnlFoto.setBackground(new java.awt.Color(153, 153, 153));
        pnlFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlFotoLayout = new javax.swing.GroupLayout(pnlFoto);
        pnlFoto.setLayout(pnlFotoLayout);
        pnlFotoLayout.setHorizontalGroup(
            pnlFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFotoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlFotoLayout.setVerticalGroup(
            pnlFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFotoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlPrincipal.add(pnlFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 110, 130));

        btnEscImagem.setText("Escolher Imagem");
        btnEscImagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEscImagemMouseClicked(evt);
            }
        });
        pnlPrincipal.add(btnEscImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 540, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        gravar();
    }//GEN-LAST:event_btnSalvarMouseClicked

    private void edtDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtDataNascimentoActionPerformed

    private void btnEscImagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEscImagemMouseClicked
        //escolher imagem
        File arquivo = Util.escolherImagem();

        //carregar a imagem
        if (arquivo != null) {
            Icon icone = Util.converterFileToIcon(arquivo);
            
            Icon iconNovo = Util.redimensionarImageIcon(icone, 108, 128);
            imgFoto.setIcon(iconNovo);
        }
    }//GEN-LAST:event_btnEscImagemMouseClicked

    private void gravar() {
        if (!verificarCampos()) {
            return;
        }
        Usuario usu = new Usuario();
        usu.setNome(edtNome.getText());
        usu.setEmail(edtEmail.getText());
        usu.setSenha(Util.calcularHash(new String(edtSenha.getPassword())));
        usu.setDatanasc(Util.converterStringToDate(edtDataNascimento.getText()));
        usu.setAtivo(chkAtivo.isSelected());
        usu.setImagem(imgFoto.getIcon());

        UsuarioController controller = new UsuarioController();
        if (controller.inserir(usu)) {
            JOptionPane.showMessageDialog(null, "Usuário inserido");
            this.dispose();
        }
    }

    private boolean verificarCampos() {
        if (edtNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo 'nome' em branco");
            return false;
        }
        if (edtEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo 'email' em branco");
            return false;
        }
        if (new String(edtSenha.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite uma senha válida");
            return false;
        }

        //^ - Inicio de linha
        //$ - final de linha
        //[] - conjunto de caracteres
        //+ - quantidades de vezes que o conjunto pode aparecer
        //+ - 1 ou mais vezes
        //{5} - 5 vezes
        //{2} - 2 vezes
        if (!edtNome.getText().matches("^[\\p{L}]+$")) {
            JOptionPane.showMessageDialog(null, "O campo 'nome' não possui o formato");
            return false;
        }

        if (!edtEmail.getText().matches("^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$")) {
            JOptionPane.showMessageDialog(null, "O campo 'email' não possui o formato");
            return false;
        }

        if (!edtDataNascimento.getText().matches("^[0-9]{2}/[0-9]{2}/[0-9]{4}$")) {
            JOptionPane.showMessageDialog(null, "Data inválida!");
            return false;
        }
        if (new String(edtSenha.getPassword()).length() < 6) {
            JOptionPane.showMessageDialog(null, "A senha deve ser maior que 6 digitos");
            return false;
        }

        String senha = new String(edtSenha.getPassword());
        String confimaSenha = new String(edtConfirmarSenha.getPassword());
        if (!senha.equals(confimaSenha)) {
            JOptionPane.showMessageDialog(null, "A senhas devem ser iguais");
            return false;
        }

        return true;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrCadUsuario dialog = new FrCadUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEscImagem;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox chkAtivo;
    private javax.swing.JPasswordField edtConfirmarSenha;
    private javax.swing.JFormattedTextField edtDataNascimento;
    private javax.swing.JTextField edtEmail;
    private javax.swing.JTextField edtNome;
    private javax.swing.JPasswordField edtSenha;
    private javax.swing.JLabel imgFoto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCadastro;
    private javax.swing.JLabel lblConfirmarSenha;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha1;
    private javax.swing.JPanel pnlFoto;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
